import { Category } from "./models/recipe-category";
import { RecipeAttrs } from "./models/recipe";

export const seeds: RecipeAttrs[] = [
  {
    title: "Guo Bao Rou (Crispy Sweat & Sour Pork)",
    popularity: 5,
    description:
      "When you talk about Northeastern Chinese cuisine with your Chinese friend, the first dish they are going to mention is Guo Bao Rou. Guo Bao Rou is a traditional dish that originated in Harbin, China, and it is now one of the most famous representatives of Northeastern Chinese cuisine. ",
    ingredients: [
      "1.3 lbs of pork loin ",
      "carrot",
      "scallion",
      "ginger",
      "cilantro",
      "garlic",
      "vegtable oil",
      "potato starch",
      "soy sauce",
      "Sichuan peper powder",
      "salt",
      "sugar",
      "vinegar",
      "Shanxi mature vinegar (can be substituted with balsamic vinegar)",
      "rice vinegar",
    ],
    steps: [
      "Cut the pork tenderloin into slices. The slices should be 5-7 mm thick. The pork slices should be around 7cm long and 5cm wide for the best result. ",
      "Shred half stalk of scallion, one tiny piece of ginger, one tiny piece of carrot, and 6-7 pieces of celery stalks. Slice 1-2 cloves of garlic. ",
      "Place the pork slices into a large bowl. Add 1 tablespoon of soy sauce, 1 teaspoon of salt, 1 teaspoon of Sichuan peppercorn, and 1 teaspoon of water. Use your hand to mix everything for 1 minute so the meat fully absorbs the flavor. ",
      "In another bowl, add 90 grams of sugar, 75 grams of white vinegar, 10 grams of Shanxi mature vinegar (or balsamic vinegar), 10 grams of rice vinegar, half a teaspoon of salt, half a teaspoon of sesame oil,  and 2 teaspoons of soy sauce. Mix the mixture well, and then add a clove of garlic slices.",
      "In the bowl with pork slices, add 75 grams of vegetable oil, 200 grams of potato starch, and 240 grams of water. Mix everything together with your hand so the mixture coat every slice of pork.",
      "In a large pot or wok, heat the vegetable oil. When the oil reaches 392 °F (200 °C), add the pork slice by slice into the oil to fry them until lightly golden. It is recommended to fry half of the pork first and then fry the latter half.",
      "Reheat the oil to 445 °F (230 °C), and refry all the pork slices until they become deep golden. ",
      "Use a large frying pan or a wok. Heat 3-4 tablespoons of oil. Add the shredded scallion, ginger, carrot, celery stalks, and garlic slices into the pan. When you smell the fragrance, add the fried pork slice to the pan. Mix everything well and cook for around 20 seconds.",
      "Add the sauce mixture inside the pan; mix everything as fast as possible until the sauce is evenly coated on the meat slices. ",
      "Take everything out and start plating. ",
    ],
    category: [Category.PORK, Category.MAIN_DISH],
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=U3JHL-F7y5Y&t=469s",
    must_know: true,
  },
  {
    title: "Potato braise eggplant",
    popularity: 5,
    description:
      "Potato braise eggplant is one of every Northeastern Chinese family's most famous home recipes. Although it looks unappetizing, it is incredibly delicious when served with rice or rice porridge. Additionally, it is so easy to cook, and the ingredient can be found in almost every grocery store. ",
    ingredients: [
      "eggplant",
      "potato",
      "pork belly",
      "garlic",
      "ginger",
      "scallion",
      "green bell pepper",
      "cilantro",
      "salt",
      "Chinese soy bean paste",
      "soy sauce",
    ],
    steps: [
      "Optionally peel the eggplants, and cut 2-3 eggplants into uniform stripes. Cut the pork belly into slices. ",
      "(Optional) Add 1 tablespoon of salt to a bowl of water. Soak the eggplant strips in salt water for ten minutes to prevent them from being oxidized. After ten minutes, take out the eggplant strips and lightly squeeze out the water.  ",
      "Chop 2 stalks of scallions, 1 tiny piece of ginger, and several cloves of garlic into mince. Chop several stalks of cilantro and half of green bell pepper into small pieces. Take one large potato, and cut it into medium pieces.  ",
      "Add several tablespoons of vegetable oil to a large frying pan or a walk. Lightly heat the oil, and then add the eggplant strips. Cook the eggplant strips for five minutes or until you see some golden brown crust on the strips. ",
      "Take the eggplant stripe out. In the same pan, add several teaspoons of vegetable oil and then add the pork belly slices. Use medium-high heat to cook the oil out from the pork belly. ",
      "When the pork belly becomes lightly golden brown, add previously chopped ginger, half of chopped scallion and garlic. Mix everything up nicely, and when you smell the fragrance, add the chopped potatoes. ",
      "Cook for 3-4 minutes, and then add 1 tablespoon of soy bean paste, 2 tablespoon of soy sauce, and the pre-cooked eggplant stripes. Cook everything for another 4-5 minutes.",
      "Add water (chicken stock) so that 2/3 of the mixture is under the liquid. Boil the liquid, turn the heat off to medium-low, and put on the lid. Simmer everything for 15-20 minutes.",
      "Take off the lid and mix everything up. Taste the sauce and add optionally add more salt or soy sauce. Turn the heat off low and add the chopped bell pepper, cilantro, and the other half of the garlic and scallion. Put on the lid and let it cook for 2-3 minutes. ",
      "Mix everything up and start plating. ",
    ],
    category: [Category.PORK, Category.VEGETABLE, Category.MAIN_DISH],
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=hrhtZo4gyl8",
    must_know: true,
  },
  {
    title: "Green pepper and dry bean curd",
    popularity: 4.5,
    description:
      "This dish is super common in every Northeastern Chinese family. It is simple to make and can be done in under 10 minutes. This dish serves well with rice or porridge. ",
    ingredients: [
      "dry bean curd (may called tofu skin)",
      "green bell pepper",
      "pork belly",
      "ginger",
      "scallion",
      "Chinese cooking wine",
      "soy sauce",
      "salt",
      "potato starch",
    ],
    steps: [
      "Cut 2 green bell pepper into medium chunks. Cut the 7-8 sheets of dry bean curd into stripes and a medium piece of pork belly into slices. ",
      "Chop 1 stalk of scallions, 1 tiny piece of ginger into mince. ",
      "Boil a pot of water, add the cut dry bean curd into the pot, and cook them for 2 minutes. After 2 minutes, take the cooked dry bean curd out and soak them in tap water for several minutes. ",
      "In a large frying pan or a wok, add 2 tablespoons of vegetable oil. Heat the oil for a minute and add the pork belly slices. Cook the pork belly until they are golden brown. ",
      "Add chopped ginger and scallion, and cook for 1-2 minutes until you smell the fragrance. Add 1 tablespoon of Chinese cooking wine and 2 tablespoons of soy sauce. Cook for another 1-2 minutes. ",
      "Add about 250 mL of water (chicken stock) and the dry bean curd inside and mix everything up. Taste the sauce and add optionally add more salt or soy sauce. ",
      "Add the chopped green bell pepper, put on the lid, and simmer everything for 2-3 minutes. ",
      "Mix 1 tablespoon of water and 1 tablespoon of water. Add the mixture inside. Cook for 1-2 minutes until the sauce sticks to the dry bean curd. Then take everything out and start plating. ",
    ],
    category: [Category.PORK, Category.VEGETABLE, Category.SIDE_DISH],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=m8Y2LfyJDiQ",
  },
  {
    title: "Northeastern braised lamb",
    popularity: 4,
    description:
      "This is a warm and delicious lamb dish that is especially good for serving in winter. When you have beloved friends or guests come for a visit, try to cook this dish and give them a big big surprise!",
    ingredients: [
      "Lamb leg",
      "star anisee",
      "ginger",
      "scallion",
      "Sichuan pepper corn",
    ],
    steps: [
      "Cut 3 lbs of lamb leg into large chunks. Mix the chunks with 3-4 tablespoons of soy sauce to marinate the lamb for 5-10 minutes. ",
      "Cut 2 stalks of scallions into large chunks, and slice 1 tiny piece of ginger.",
      "In a large frying pan or a walk, add 4-5 tablespoons of vegetable oil and heat them. Add the lamb chunks and cook them until they are golden brown. ",
      "Add 3 star anise, one tablespoon of Sichuan peppercorn, the previously cut scallion, and ginger into a large pot. Add the cooked lamb and water so that the lamb chunks are under the liquid. Then add 1-2 tablespoons of salt. ",
      "Boil everything up and then turn down the heat to simmer the mixture for 2 hours. ",
      "After the lamb becomes soft and tender, add 1-2 tablespoons of soy sauce, 1 tablespoon of sugar inside the pot. Turn the heat up to reduce the juices. ",
      "Take everything out and start plating",
    ],
    category: [Category.LAMB, Category.MAIN_DISH],
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=jq8WiiG1Ik8&t=408s",
  },
  {
    title: "Northeastern braised potatos with beef",
    popularity: 4,
    description:
      "Tired of beef stew? Try this authentic Northeastern potato braised beef. This dish is super delicious and simple to make. Basically, all you need to do is prepare the ingredient and wait. This dish should be served with rice and will absolutely give you a 'WOW' moment!",
    ingredients: [
      "beef sirloin/shank/brisket",
      "potato",
      "star anisee",
      "sichuan peppercorn",
      "scallion",
      "ginger",
      "garlic",
      "Bixian chili bean paste",
      "Chinese cooking wine",
      "soy souce",
    ],
    steps: [
      "Cut 2-3 lbs of beef sirloin/shank/brisket into medium-large chunks. Cut 1 large potato into medium-large chunks. ",
      "Cut 1 stalk of scallion into medium chunks and cut 1 tiny piece of ginger into slices. ",
      "Add tap water into a large pot, put the cut beef inside the pot, and boil them up. Then remove the meat and optionally wash off the blood foam/dirty stuff. ",
      "In a large frying pan or a wok, heat 3-4 tablespoons of vegetable oil. Add 1 star anise, 10-15 Sichuan pepper corn, and the chopped scallion and ginger. When you smell the fragrance, add the chili bean paste. Cook everything for 1 minute. ",
      "Add the beef chunks, cook everything for 2-3 minutes until the sauce is evenly coated on the beef. Then add 3-4 tablespoons of Chinese cooking wine and 1 tablespoon of soy sauce. Cook everything for 2 minutes. ",
      "Add hot water into the pan until everything is under the liquid. Add 1-2 tablespoons of salt and 1 teaspoon of sugar. Bring up to boil",
      "Put on the lid and simmer for 2-3 hours (40-60 minutes for pressure cooker)",
      "After the beef becomes soft and tender, add chopped potatoes inside. If there is not enough liquid inside, add more water accordingly. Put on the lid and boil for 15-20 minutes. ",
      "Chopp 1 bell pepper into medium chunks, dice one stalk of scallion and 2-3 cloves of garlic, and add them to the pan. Put on the lid and let everything simmer for 1-2 minutes. ",
      "If too much liquid is inside, reduce the juice for 3-5 minutes. Mix everything up nicely and start plating. ",
    ],
    category: [Category.BEEF, Category.MAIN_DISH],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=hPtxD5lx2Dc&t=9s",
  },
  {
    title: "Northeastern red braised fish",
    popularity: 4.5,
    description:
      "How do you normally cook fish? Fry them? Eat them raw? Give a try of this famous Chinese fish recipe! This dish will appear on the table when Chinese people celebrate a festival! It will never let you down!",
    ingredients: [
      "whole carp (can be substitued with other types of fish)",
      "star anisee",
      "Sichuan peppercorn",
      "scallion",
      "ginger",
      "dry chilly",
      "soy sauce",
      "salt",
      "vegtable oil",
      "pork lard",
      "Chinese cooking wine",
      "Shanxi mature vinegar (can be substituted with balsamic vinegar)",
    ],
    steps: [
      "Cut slices on double sides of the fish. Then marinate the fish with 1 tablespoon of salt and 1 tablespoon of soy sauce for 15 minutes. Dry the fish with a clean towel or a paper towel",

      "Cut 1 stalk of scallion into medium chunks and cut 1 tiny piece of ginger into slices. ",
      "Heat 5-6 tablespoons of oil inside a large frying pan or a wok. If not using a non-stick pan, add a pinch of salt to the pan to avoid stickiness. Fry both sides of the fish until golden brown. ",
      "Add 1-2 star anises, one tablespoon of Sichuan peppercorn, previously chopped scallion, and ginger inside. Optionally add 1 tablespoon of pork lard. ",
      "When you smell the fragrance, add 2 tablespoons of Chinese cooking wine, 2 tablespoons of soy sauce, and 1 teaspoon of salt.  Mix everything up and then add water until half of the fish is immersed in the liquid. ",
      "Boil the mixture up and then add 1 tablespoon of vinegar. Put on the lid and simmer the fish for 12-15 minutes. ",
      "Take off the lid and take out all the spices. Take out the fish into a large plate. Add 1 tablespoon of sugar inside the sauce and start to reduce the sauce. Optionally add some starch water inside for extra stickiness. ",
      "Pour the sauce on the fish and serve. ",
    ],
    category: [Category.FISH, Category.MAIN_DISH],
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=SspF5BhlLac&t=430s",
  },
  {
    title: "North Eastern egg fried sause noodle",
    popularity: 4,
    description:
      "This dish is delicious, fast, and simple to make. You can finish everything up in under 5 minutes and enjoy an easy but flavorful noodles dinner!",
    ingredients: [
      "egg",
      "soy bean paste",
      "green bell pepper, scallion, dry noodles",
    ],
    steps: [
      "Dice 2 stalks of scallion and half of green bell pepper. ",
      "Heat 5-6 tablespoons of oils inside a large frying pan or a wok. Wisk 4-5 eggs and fry them. As your fry them, cut the egg into tiny pieces. When the eggs are lightly golden brown, take them out. ",
      "Add 3-4 tablespoons of oil and heat the pan. Then add the chopped scallion and green pepper inside. When you smell the fragrance, add 3-4 tablespoons of soy bean paste and cook everything for 2-3 minutes ",
      "Add 200ml of water and the cooked egg inside and boil for 2-3 minutes. Then add 2 tablespoons of starch water inside. Mix everything up for preferred sauce stickiness.",
      "To serve, pour some sauce on freshly boiled noodles. ",
    ],
    category: [Category.NOODLE, Category.VEGAN_FRIENDLY, Category.MAIN_DISH],
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=LufARlY6CAw&t=282s",
  },
  {
    title: "chicken braised hazel mushroom",
    popularity: 5,
    description:
      "This is the 'soal' of Northeastern Chinese cuisine. This dish is so famous that almost every single Chinese person knows it. This dish is super delicious and simple to make! The only difficulty might be to buy the dry hazel mushroom. If you find it somewhere, do not hesitate and give this recipe a try!",
    ingredients: [
      "Dry hazel mushroom",
      "One whole chicken (or 4-5 chicken thighs)",
      "Vermicelli (optional)",
      "sichuan peppercorn, scallion, ginger, star anise",
      "soy sauce",
    ],
    steps: [
      "Soak the dry hazel mushroom in tap water for 30 minutes. Then wash the mushroom to remove any excess dirt (keep the mushroom soaked water). ",
      "Cut the chicken into medium chunks. Cut 2 stalks of scallions into large chunks and 1 tiny piece of ginger into slices. ",
      "Heat 5-6 tablespoons of oil inside a large frying pan or a wok. Add 2 star anises, 1 tablespoon of Sichuan peppercorn, and the diced scallion and ginger. Cook until you smell the fragrance",
      "Add the hazel mushroom and the soaked water. Add extra water until everything is under the liquid. Bring the mixture up to a boil. ",
      "Put on the lid and simmer for 1 hour (20-25 minutes for pressure cookers)",
      "Optionally add vermicelli, and start to reduce the juice down to the amount that can fit in a large bowl. Add salt accordingly. ",
      "Take everything out and start serving. ",
    ],
    category: [Category.CHICKEN, Category.MAIN_DISH],
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=22ITW8TuYLI&t=8s",
    must_know: true,
  },
  {
    title: "sesame sause noodle",
    popularity: 3.5,
    description: "quick and easy noodle",
    ingredients: [
      "cucumber",
      "radish",
      "cilantro",
      "scallion",
      "bean sprout",
      "sichuan peppercorn, start anise, sesame paste",
      "vegetable oil ",
    ],
    steps: [
      "Chop 1 stalk of scallion, and 5-6 stalks of cilantro into small pieces, Shred 1-2 baby cucumbers and 1-2 baby radishes. ",
      "Chop another 1 stack of onion into chunks and slice one tiny piece of ginger. ",
      "Heat 4-5 tablespoons of vegetable oil in a frying pan or a wok. Then add 2 star anises, 1 tablespoon of Sichuan peppercorn, chopped scallion chunks, and ginger slices inside. Cook until the spices are golden brown, then add 4-5 tablespoons of water. Mix well and take everything out for later use. ",
      "Boil water in a pot, then add the bean sprout inside. Cook for 1 minute and take them out for later use. ",
      "In a bowl, add 3 tablespoons of peanut butter, 3 tablespoons of sesame sauce. Then filter out all the spices from the water-oil mixture and add the mixture inside. Then add 1 teaspoon of salt and 1 tablespoon of water, and mix well.",
      "To serve, add the shredded cucumber and radish to the freshly cooked noodle. Pour 1-2 tablespoons of sauce on the noodle and mix. ",
    ],
    category: [
      Category.NOODLE,
      Category.VEGAN_FRIENDLY,
      Category.VEGETABLE,
      Category.MAIN_DISH,
    ],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=Uhzf44elze8&t=432s",
  },
  {
    title: "egg fried rice",
    popularity: 5,
    description: "famous and easy rice",
    ingredients: ["rice", "cucumber", "carrot", "scallion"],
    steps: ["cut veggies", "fried rice"],
    category: [Category.RICE, Category.MAIN_DISH],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=BoGLmT-vFos",
  },
  {
    title: "Candied Sweet potato",
    popularity: 5,
    description: "the most famous dongbei dessert",
    ingredients: ["sweet potato", "sugar"],
    steps: ["cut and fry sweet potato", "cook sugar", "mix"],
    category: [
      Category.DESSERT,
      Category.SIDE_DISH,
      Category.VEGAN_FRIENDLY,
      Category.VEGETABLE,
    ],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=udjW6A3jUjA",
    must_know: true,
  },
  {
    title: "scallion mix tofu",
    popularity: 4,
    description: "delicious and fragrent appetizer",
    ingredients: ["tofu", "scallion", "cilantro"],
    steps: ["cut scallion, tofu, and cilantro", "boil tofu", "mix together"],
    category: [
      Category.APPETIZER,
      Category.SIDE_DISH,
      Category.VEGAN_FRIENDLY,
      Category.VEGETABLE,
    ],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=QDljyhAEa00&t=11s",
  },
  {
    title: "spicy fried clams",
    popularity: 4,
    description: "spicy and fragrent seafood dish",
    ingredients: ["clams", "dry chilli", "garlic"],
    steps: ["boil clams", "fried chilli and garlic", "mix together"],
    category: [Category.SEAFOOD, Category.SIDE_DISH],
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=c1SmAXSqkmI",
  },
];
