import { Category, Type } from "./models/recipe-category";
import { RecipeAttrs } from "./models/recipe";

export const seeds: RecipeAttrs[] = [
  {
    title: "Sweat and Sour Pork",
    popularity: 5,
    description:
      "When it comes to Northeastern Chinese cuisine, this dish will definitely be mentioned. It is one of the most famous dishes in Northeastern Chinese cuisine and is also considered the soul of Northeastern cuisine.",
    difficulity: 5,
    image: "GuoBaoRou",
    ingredients: [
      "1.3 lbs of pork loin ",
      "carrot",
      "scallion",
      "ginger",
      "cilantro",
      "garlic",
      "vegtable oil",
      "potato starch",
      "soy sauce",
      "Sichuan peper powder",
      "salt",
      "sugar",
      "vinegar",
      "Shanxi mature vinegar (can be substituted with balsamic vinegar)",
      "rice vinegar",
    ],
    steps: [
      "Cut the pork tenderloin into slices. The slices should be 5-7 mm thick. The pork slices should be around 7cm long and 5cm wide for the best result. ",
      "Shred half stalk of scallion, one tiny piece of ginger, one tiny piece of carrot, and 6-7 pieces of celery stalks. Slice 1-2 cloves of garlic. ",
      "Place the pork slices into a large bowl. Add 1 tablespoon of soy sauce, 1 teaspoon of salt, 1 teaspoon of Sichuan peppercorn, and 1 teaspoon of water. Use your hand to mix everything for 1 minute so the meat fully absorbs the flavor. ",
      "In another bowl, add 90 grams of sugar, 75 grams of white vinegar, 10 grams of Shanxi mature vinegar (or balsamic vinegar), 10 grams of rice vinegar, half a teaspoon of salt, half a teaspoon of sesame oil,  and 2 teaspoons of soy sauce. Mix the mixture well, and then add a clove of garlic slices.",
      "In the bowl with pork slices, add 75 grams of vegetable oil, 200 grams of potato starch, and 240 grams of water. Mix everything together with your hand so the mixture coat every slice of pork.",
      "In a large pot or wok, heat the vegetable oil. When the oil reaches 392 °F (200 °C), add the pork slice by slice into the oil to fry them until lightly golden. It is recommended to fry half of the pork first and then fry the latter half.",
      "Reheat the oil to 445 °F (230 °C), and refry all the pork slices until they become deep golden. ",
      "Use a large frying pan or a wok. Heat 3-4 tablespoons of oil. Add the shredded scallion, ginger, carrot, celery stalks, and garlic slices into the pan. When you smell the fragrance, add the fried pork slice to the pan. Mix everything well and cook for around 20 seconds.",
      "Add the sauce mixture inside the pan; mix everything as fast as possible until the sauce is evenly coated on the meat slices. ",
      "Take everything out and start plating. ",
    ],
    category: Category.PORK,
    type: Type.MAIN_DISH,
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=U3JHL-F7y5Y&t=469s",
    must_know: true,
  },
  {
    title: "Potato braise eggplant",
    image: "TuDouDunQieZi",
    description:
      "This dish is a famous Northeastern home-cooked meal. Although it may not look visually appealing, it is undoubtedly delicious. This dish pairs very well with steamed rice.",
    popularity: 5,
    difficulity: 2,
    ingredients: [
      "eggplant",
      "potato",
      "pork belly",
      "garlic",
      "ginger",
      "scallion",
      "green bell pepper",
      "cilantro",
      "salt",
      "Chinese soy bean paste",
      "soy sauce",
    ],
    steps: [
      "Optionally peel the eggplants, and cut 2-3 eggplants into uniform stripes. Cut the pork belly into slices. ",
      "(Optional) Add 1 tablespoon of salt to a bowl of water. Soak the eggplant strips in salt water for ten minutes to prevent them from being oxidized. After ten minutes, take out the eggplant strips and lightly squeeze out the water.  ",
      "Chop 2 stalks of scallions, 1 tiny piece of ginger, and several cloves of garlic into mince. Chop several stalks of cilantro and half of green bell pepper into small pieces. Take one large potato, and cut it into medium pieces.  ",
      "Add several tablespoons of vegetable oil to a large frying pan or a walk. Lightly heat the oil, and then add the eggplant strips. Cook the eggplant strips for five minutes or until you see some golden brown crust on the strips. ",
      "Take the eggplant stripe out. In the same pan, add several teaspoons of vegetable oil and then add the pork belly slices. Use medium-high heat to cook the oil out from the pork belly. ",
      "When the pork belly becomes lightly golden brown, add previously chopped ginger, half of chopped scallion and garlic. Mix everything up nicely, and when you smell the fragrance, add the chopped potatoes. ",
      "Cook for 3-4 minutes, and then add 1 tablespoon of soy bean paste, 2 tablespoon of soy sauce, and the pre-cooked eggplant stripes. Cook everything for another 4-5 minutes.",
      "Add water (chicken stock) so that 2/3 of the mixture is under the liquid. Boil the liquid, turn the heat off to medium-low, and put on the lid. Simmer everything for 15-20 minutes.",
      "Take off the lid and mix everything up. Taste the sauce and add optionally add more salt or soy sauce. Turn the heat off low and add the chopped bell pepper, cilantro, and the other half of the garlic and scallion. Put on the lid and let it cook for 2-3 minutes. ",
      "Mix everything up and start plating. ",
    ],
    category: Category.VEGETABLE,
    type: Type.MAIN_DISH,
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=hrhtZo4gyl8",
    must_know: true,
  },
  {
    title: "Green pepper and dry bean curd",
    image: "JianJiaoGanDouFu",
    description:
      "A typical home-cooked dish in Northeastern Chinese cuisine. It uses healthy ingredients, is easy to prepare, and is incredibly delicious.",
    popularity: 4.5,
    difficulity: 2,
    ingredients: [
      "dry bean curd (may called tofu skin)",
      "green bell pepper",
      "pork belly",
      "ginger",
      "scallion",
      "Chinese cooking wine",
      "soy sauce",
      "salt",
      "potato starch",
    ],
    steps: [
      "Cut 2 green bell pepper into medium chunks. Cut the 7-8 sheets of dry bean curd into stripes and a medium piece of pork belly into slices. ",
      "Chop 1 stalk of scallions, 1 tiny piece of ginger into mince. ",
      "Boil a pot of water, add the cut dry bean curd into the pot, and cook them for 2 minutes. After 2 minutes, take the cooked dry bean curd out and soak them in tap water for several minutes. ",
      "In a large frying pan or a wok, add 2 tablespoons of vegetable oil. Heat the oil for a minute and add the pork belly slices. Cook the pork belly until they are golden brown. ",
      "Add chopped ginger and scallion, and cook for 1-2 minutes until you smell the fragrance. Add 1 tablespoon of Chinese cooking wine and 2 tablespoons of soy sauce. Cook for another 1-2 minutes. ",
      "Add about 250 mL of water (chicken stock) and the dry bean curd inside and mix everything up. Taste the sauce and add optionally add more salt or soy sauce. ",
      "Add the chopped green bell pepper, put on the lid, and simmer everything for 2-3 minutes. ",
      "Mix 1 tablespoon of water and 1 tablespoon of water. Add the mixture inside. Cook for 1-2 minutes until the sauce sticks to the dry bean curd. Then take everything out and start plating. ",
    ],
    category: Category.SOY,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=m8Y2LfyJDiQ",
  },
  {
    title: "Northeastern braised lamb",
    image: "HongMenYangRou",
    description:
      "This is a delicious lamb dish. While removing the gaminess of the lamb, it retains the freshness of the meat. This dish will certainly warm your stomach during the cold winter days.",
    popularity: 4,
    difficulity: 3,
    ingredients: [
      "Lamb leg",
      "star anisee",
      "ginger",
      "scallion",
      "Sichuan pepper corn",
    ],
    steps: [
      "Cut 3 lbs of lamb leg into large chunks. Mix the chunks with 3-4 tablespoons of soy sauce to marinate the lamb for 5-10 minutes. ",
      "Cut 2 stalks of scallions into large chunks, and slice 1 tiny piece of ginger.",
      "In a large frying pan or a walk, add 4-5 tablespoons of vegetable oil and heat them. Add the lamb chunks and cook them until they are golden brown. ",
      "Add 3 star anise, one tablespoon of Sichuan peppercorn, the previously cut scallion, and ginger into a large pot. Add the cooked lamb and water so that the lamb chunks are under the liquid. Then add 1-2 tablespoons of salt. ",
      "Boil everything up and then turn down the heat to simmer the mixture for 2 hours. ",
      "After the lamb becomes soft and tender, add 1-2 tablespoons of soy sauce, 1 tablespoon of sugar inside the pot. Turn the heat up to reduce the juices. ",
      "Take everything out and start plating",
    ],
    category: Category.LAMB,
    type: Type.MAIN_DISH,
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=jq8WiiG1Ik8&t=408s",
  },
  {
    title: "Northeastern braised potatos with beef",
    image: "TuDouDunNiuRou",
    description:
      "This is a famous slow-cooked beef dish. Tender beef paired with creamy potatoes. This dish will surely impress you and your family.",
    popularity: 4,
    difficulity: 3,
    ingredients: [
      "beef sirloin/shank/brisket",
      "potato",
      "star anisee",
      "sichuan peppercorn",
      "scallion",
      "ginger",
      "garlic",
      "Bixian chili bean paste",
      "Chinese cooking wine",
      "soy souce",
    ],
    steps: [
      "Cut 2-3 lbs of beef sirloin/shank/brisket into medium-large chunks. Cut 1 large potato into medium-large chunks. ",
      "Cut 1 stalk of scallion into medium chunks and cut 1 tiny piece of ginger into slices. ",
      "Add tap water into a large pot, put the cut beef inside the pot, and boil them up. Then remove the meat and optionally wash off the blood foam/dirty stuff. ",
      "In a large frying pan or a wok, heat 3-4 tablespoons of vegetable oil. Add 1 star anise, 10-15 Sichuan pepper corn, and the chopped scallion and ginger. When you smell the fragrance, add the chili bean paste. Cook everything for 1 minute. ",
      "Add the beef chunks, cook everything for 2-3 minutes until the sauce is evenly coated on the beef. Then add 3-4 tablespoons of Chinese cooking wine and 1 tablespoon of soy sauce. Cook everything for 2 minutes. ",
      "Add hot water into the pan until everything is under the liquid. Add 1-2 tablespoons of salt and 1 teaspoon of sugar. Bring up to boil",
      "Put on the lid and simmer for 2-3 hours (40-60 minutes for pressure cooker)",
      "After the beef becomes soft and tender, add chopped potatoes inside. If there is not enough liquid inside, add more water accordingly. Put on the lid and boil for 15-20 minutes. ",
      "Chopp 1 bell pepper into medium chunks, dice one stalk of scallion and 2-3 cloves of garlic, and add them to the pan. Put on the lid and let everything simmer for 1-2 minutes. ",
      "If too much liquid is inside, reduce the juice for 3-5 minutes. Mix everything up nicely and start plating. ",
    ],
    category: Category.BEEF,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=hPtxD5lx2Dc&t=9s",
  },
  {
    title: "Northeastern red braised fish",
    image: "HongShaoYu",
    description:
      "This is a dish famous throughout China. Perfectly seasoned with tender fish meat. It is perfect to bring out and amaze everyone at gatherings.",
    popularity: 4.5,
    difficulity: 4,
    ingredients: [
      "whole carp (can be substitued with other types of fish)",
      "star anisee",
      "Sichuan peppercorn",
      "scallion",
      "ginger",
      "dry chilly",
      "soy sauce",
      "salt",
      "vegtable oil",
      "pork lard",
      "Chinese cooking wine",
      "Shanxi mature vinegar (can be substituted with balsamic vinegar)",
    ],
    steps: [
      "Cut slices on double sides of the fish. Then marinate the fish with 1 tablespoon of salt and 1 tablespoon of soy sauce for 15 minutes. Dry the fish with a clean towel or a paper towel",

      "Cut 1 stalk of scallion into medium chunks and cut 1 tiny piece of ginger into slices. ",
      "Heat 5-6 tablespoons of oil inside a large frying pan or a wok. If not using a non-stick pan, add a pinch of salt to the pan to avoid stickiness. Fry both sides of the fish until golden brown. ",
      "Add 1-2 star anises, one tablespoon of Sichuan peppercorn, previously chopped scallion, and ginger inside. Optionally add 1 tablespoon of pork lard. ",
      "When you smell the fragrance, add 2 tablespoons of Chinese cooking wine, 2 tablespoons of soy sauce, and 1 teaspoon of salt.  Mix everything up and then add water until half of the fish is immersed in the liquid. ",
      "Boil the mixture up and then add 1 tablespoon of vinegar. Put on the lid and simmer the fish for 12-15 minutes. ",
      "Take off the lid and take out all the spices. Take out the fish into a large plate. Add 1 tablespoon of sugar inside the sauce and start to reduce the sauce. Optionally add some starch water inside for extra stickiness. ",
      "Pour the sauce on the fish and serve. ",
    ],
    category: Category.FISH,
    type: Type.MAIN_DISH,
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=SspF5BhlLac&t=430s",
  },
  {
    title: "North Eastern egg fried sause noodle",
    image: "ZhaJiangMian",
    description:
      "This is a dish of noodles that can be prepared very quickly. Despite its simple ingredients, it tastes amazing. It's perfect for a quick and delicious lunch when you are in a hurry.",
    popularity: 3.5,
    difficulity: 1,
    ingredients: [
      "egg",
      "soy bean paste",
      "green bell pepper, scallion, dry noodles",
    ],
    steps: [
      "Dice 2 stalks of scallion and half of green bell pepper. ",
      "Heat 5-6 tablespoons of oils inside a large frying pan or a wok. Wisk 4-5 eggs and fry them. As your fry them, cut the egg into tiny pieces. When the eggs are lightly golden brown, take them out. ",
      "Add 3-4 tablespoons of oil and heat the pan. Then add the chopped scallion and green pepper inside. When you smell the fragrance, add 3-4 tablespoons of soy bean paste and cook everything for 2-3 minutes ",
      "Add 200ml of water and the cooked egg inside and boil for 2-3 minutes. Then add 2 tablespoons of starch water inside. Mix everything up for preferred sauce stickiness.",
      "To serve, pour some sauce on freshly boiled noodles. ",
    ],
    category: Category.NOODLE,
    type: Type.MAIN_DISH,
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=LufARlY6CAw&t=282s",
  },
  {
    title: "Chicken braised hazel mushroom",
    image: "XiaoJiDunMoGu",
    popularity: 5,
    description:
      "This dish is one of the most famous Northeastern Chinese dishes. Serving this dish when guests come to visit represents the utmost importance and respect for the guests. Moreover, this dish is also incredibly delicious.",
    difficulity: 3,
    ingredients: [
      "Dry hazel mushroom",
      "One whole chicken (or 4-5 chicken thighs)",
      "Vermicelli (optional)",
      "sichuan peppercorn, scallion, ginger, star anise",
      "soy sauce",
    ],
    steps: [
      "Soak the dry hazel mushroom in tap water for 30 minutes. Then wash the mushroom to remove any excess dirt (keep the mushroom soaked water). ",
      "Cut the chicken into medium chunks. Cut 2 stalks of scallions into large chunks and 1 tiny piece of ginger into slices. ",
      "Heat 5-6 tablespoons of oil inside a large frying pan or a wok. Add 2 star anises, 1 tablespoon of Sichuan peppercorn, and the diced scallion and ginger. Cook until you smell the fragrance",
      "Add the hazel mushroom and the soaked water. Add extra water until everything is under the liquid. Bring the mixture up to a boil. ",
      "Put on the lid and simmer for 1 hour (20-25 minutes for pressure cookers)",
      "Optionally add vermicelli, and start to reduce the juice down to the amount that can fit in a large bowl. Add salt accordingly. ",
      "Take everything out and start serving. ",
    ],
    category: Category.CHICKEN,
    type: Type.MAIN_DISH,
    recipe_provider_name: "老东北美食",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=22ITW8TuYLI&t=8s",
    must_know: true,
  },
  {
    title: "Sesame sause noodle",
    image: "ZhiMaLiangMian",
    popularity: 3.5,
    description:
      "This is a healthy, delicious, and quick-to-make cold noodle dish. It's perfect for preparing and satisfying your appetite during hot summer days.",
    difficulity: 1,
    ingredients: [
      "cucumber",
      "radish",
      "cilantro",
      "scallion",
      "bean sprout",
      "sichuan peppercorn, start anise, sesame paste",
      "vegetable oil ",
    ],
    steps: [
      "Chop 1 stalk of scallion, and 5-6 stalks of cilantro into small pieces, Shred 1-2 baby cucumbers and 1-2 baby radishes. ",
      "Chop another 1 stack of onion into chunks and slice one tiny piece of ginger. ",
      "Heat 4-5 tablespoons of vegetable oil in a frying pan or a wok. Then add 2 star anises, 1 tablespoon of Sichuan peppercorn, chopped scallion chunks, and ginger slices inside. Cook until the spices are golden brown, then add 4-5 tablespoons of water. Mix well and take everything out for later use. ",
      "Boil water in a pot, then add the bean sprout inside. Cook for 1 minute and take them out for later use. ",
      "In a bowl, add 3 tablespoons of peanut butter, 3 tablespoons of sesame sauce. Then filter out all the spices from the water-oil mixture and add the mixture inside. Then add 1 teaspoon of salt and 1 tablespoon of water, and mix well.",
      "To serve, add the shredded cucumber and radish to the freshly cooked noodle. Pour 1-2 tablespoons of sauce on the noodle and mix. ",
    ],
    category: Category.NOODLE,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=Uhzf44elze8&t=432s",
  },
  {
    title: "Napa cabbage salad",
    image: "LiangBanBaiCai",
    description:
      "This is a simple yet flavorful appetizer, made with healthy ingredients. This dish is perfect for stimulating your and your family's appetite, getting you all ready to enjoy the upcoming main course.",
    difficulity: 1,
    popularity: 4,
    ingredients: [
      "1/4 napa cabbage",
      "chili flakes (chili oil)",
      "Shanxi aged vinegar (balsamic vinegar)",
      "rice vinegar",
      "salt",
      "sugar",
    ],
    steps: [
      "Cut the napa cabbage into strips.",
      "Wash the napa cabbage strips using tap water. Make sure to filter as much water out after cleaning.",
      "Mince 5-6 cloves of garlic. If you do not have chili oil, heat 4-5 tablespoons of vegetable oil until smoking, and pour on 3-4 tablespoons of chili flakes.",
      "In a small bowl, mix the garlic mince, chili oil, 2 tablespoons of vinegar, 1 tablespoon of rice vinegar, 1 teaspoon of salt, 1 teaspoon of sugar.",
      "Mix the napa cabbage with the sauce. Taste it and optionally add more salt/vinegar according to your preference. ",
    ],
    category: Category.VEGETABLE,
    type: Type.APPETIZER,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=CABzvMWCspc",
  },
  {
    title: "Braised eggplant",
    image: "ShaoQieZi",
    description:
      "This is a very famous dish that pairs well with rice. It transforms simple eggplant into a stunning and delightful delicacy.",
    difficulity: 3,
    popularity: 4.5,
    ingredients: [
      "eggplant",
      "green pepper",
      "scallion",
      "garlic",
      "ginger",
      "Chinese cooking wine",
      "soy sauce",
      "corn starch",
    ],
    steps: [
      "Cut 3 eggplants into medium chunks. Cut 1 green pepper into medium-small chunks. ",
      "Dice 1 stalk of scallion, 1 tiny piece of ginger, and 1-3 cloves of garlic.",
      "Use a large pot or a wok, heat a decent amount of oil to 428 F (220C), and fry the eggplant. Take the eggplant out when they become light golden brown.",
      "eggplants, add the green pepper and fry them for several seconds.",
      "In a large frying pan or a wok, heat 3-4 tablespoons of oil. Add the scallion, ginger, and garlic to fry them.",
      "When you smell the fragrance, add 2 tablespoons of Chinese cooking wine and 2 tablespoons of soy sauce.",
      "When the alcohol evaporates, add the fried eggplants and green pepper and cook for 2-3 minutes.",
      "Add 5-6 tablespoons of water, 1 teaspoon of salt, 1 tablespoon of sugar, and 1 teaspoon of msg (optional).",
      "In a small bowl, mix 1 teaspoon of cornstarch and 2-3 teaspoons of water. Add the starch water to the pan and mix everything well.",
      "Take everything out and start plating.",
    ],
    category: Category.VEGETABLE,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=wWfGpKCkHRg",
  },
  {
    title: "Stir-fried Eggs with Chinese Chives",
    image: "JiuCaiChaoJiDan",
    description:
      "This is a dish with simple ingredients, rich in nutrients, and easy to make. It pairs excellently with rice and wraps, such as tortillas or pancakes.",
    popularity: 3,
    difficulity: 2,
    ingredients: ["Garlic chives", "eggs", "salt", "potato starch"],
    steps: [
      "Wash the garlic chives and cut them into 4-5 cm sections. Separate the leaves and the roots after cutting. ",
      "Crack 4-5 eggs in a bowl. Add 1 tablespoon of water, 1 teaspoon of potato starch, half a teaspoon of water, and then whisk the mixture. ",
      "In a large frying pan or a wok, heat 5-6 tablespoons of vegetable oil. Fry the egg mixture until both sides are golden brown. Cut the egg into large pieces using a spatula or spoon.",
      "Take the egg out and reheat 3-4 tablespoons of vegetable oil.",
      "Add the root of the garlic chives and fry for 1-2 minutes. While frying, add 1 teaspoon of salt.",
      "Add the garlic chive leaves and fry for another 1-2 minutes. Then add the fried egg and fry for another 1 minute.",
      "Take everything out and start plating. ",
    ],
    category: Category.VEGETABLE,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=rwYJxfJVVlU",
  },
  {
    title: "Stir-fried Eggs with Onions",
    image: "YangCongChaoJiDan",
    description:
      "This is a simple home-cooked dish, made with basic ingredients, rich in nutrients, and very easy to prepare. It pairs perfectly with steamed rice, making it incredibly appetizing.",
    popularity: 3,
    difficulity: 2,
    ingredients: [
      "egg",
      "onion",
      "Sichuan pepper powder",
      "soy sauce",
      "salt",
      "Chinese cooking wine",
    ],
    steps: [
      "Slice 2 onions into thin stripes. Crack and whisk 4-5 eggs with 1/2 teaspoon of salt. ",
      "Heat 5-6 tablespoons of vegetable oil in a large frying pan or a wok. Fry the egg until both sides are golden brown. Cut the egg into large chunks using a spatula or a spoon.",
      "Reheat 3-4 tablespoons of vegetable oil. Add the chopped onion and cook until the onion becomes half transparent. Then add 1 teaspoon of Sichuan pepper powder, 1 tablespoon of soy sauce, 1 teaspoon of salt, 1 teaspoon of msg (optional), and 1 tablespoon of Chinese cooking wine. Mix everything well",
      "Add the fried egg inside. Mix everything well and cook for another 1-2 minutes.",
      "Take everything out and start plating. ",
    ],
    category: Category.VEGETABLE,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=mJvB7c0DeRg&t=276s",
  },
  {
    title: "Braised Chicken with Potato",
    image: "TuDouDunJiKuai",
    description:
      "A delicious dish indeed. The tender chicken and creamy potatoes are paired together perfectly, creating a delightful combination.",
    difficulity: 3,
    popularity: 4,
    ingredients: [
      "chicken drumsticks (thigh)",
      "potato",
      "red chili pepper",
      "garlic",
      "chili",
      "ginger",
      "star anise",
      "Sichuan peppercorn",
      "Chinese cooking wine",
      "soy sauce",
      "Pixian chili bean paste",
    ],
    steps: [
      "Cut the 5-6 chicken drumsticks (2-3 chicken thighs) into medium chunks. Cut 2 potatoes into medium-small chunks. Dice 1-2 red chili pepper.",
      "Cut 1 stalk of scallion into chunks, slice 1 tiny piece of ginger, and mince 5-6 cloves of garlic,",
      "Heat 6-7 tablespoons of vegetable oil in a large frying pan or a wok. Then add 2 star anises, 1 teaspoon of Sichuan peppercorn, scallion, and ginger. Cook them until you smell the fragrance, ",
      "Add the chicken inside, and cook for 2-3 minutes. Then add 2 tablespoons of Pixian chili bean paste and cook for 1 minute. ",
      "Add the potato chunks inside and cook for 2 minutes. Then add 2 tablespoons of Chinese cooking wine, 2 tablespoons of soy sauce, 1 teaspoon of salt and mix everything well. Turn down the heat and let it simmer for 2-3 minutes. ",
      "Add water so that everything is immersed in the liquid. Put on the lid and turn down the gas to let it simmer for 15-20 minutes.",
      "Take off the lid and add the garlic mince and diced red chili pepper. Put on the lid and turn up the gas to let it boil for 2-3 minutes. ",
      "Take everything out and serve. ",
    ],
    category: Category.CHICKEN,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=NUfMoj7Lsic&t=297s",
  },
  {
    title: "Tomato Tofu soup",
    image: "FanQieDouFuTang",
    description:
      "This is a soup that is both easy to make and nutritious. Even when you don't have much of an appetite, this soup will surely stimulate your taste buds and make you feel more eager to eat.",
    difficulity: 2,
    popularity: 3,
    ingredients: [
      "Egg",
      "Tomato",
      "Firm Tofu",
      "scallion",
      "ginger",
      "cilantro",
      "flour",
      "egg",
      "Chinese cooking wine",
      "soy sauce",
      "salt",
    ],
    steps: [
      "Dice 3-4 stalks of cilantro and mince 1 tiny piece of ginger. Dice 2 stalks of scallion and separate them into 3 portions.",
      "Dice 2 large tomatoes and 1/2 of firm tofu. ",
      "Place the diced tofu in a large bowl. Add 1/2 of diced ginger and 1 portion of scallion. Then add 1/2 teaspoon of salt, 2 tablespoons of flour, and 1 egg. Mix everything well together. ",
      "Heat 5-6 tablespoons of vegetable oil in a large frying pan or a wok. Add the tofu inside and cook until both sides become golden brown. ",
      "Add the remaining diced ginger and another 1 portion of scallion, and cook until you can smell the fragrance.",
      "Add diced tomato inside and 1 teaspoon of salt inside. Mix everything well and cook for 3 minutes. ",
      "Add 1 tablespoon of Chinese cooking wine and 2 tablespoons of soy sauce. Mix everything well and add water until everything is immersed in the liquid. Put on the lid and let it boil for 7-10 minutes. ",
      "Taste the soup and optionally add more salt inside. Then add the remaining 1 portion of the scallion. Mix everything well. ",
      "Take everything out and serve.",
    ],
    category: Category.SOY,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=i0BXePsVaYo",
  },
  {
    title: "Steamed chicken with minced garlic",
    image: "SuanRongZhengJi",
    description:
      "This steamed dish effectively preserves the freshness of the chicken. The garlic helps neutralize any gamey flavor, leaving only the most delightful taste in your mouth.",
    difficulity: 3,
    popularity: 3.5,
    ingredients: [
      "4 chicken leg quaters",
      "cilantro",
      "red bell pepper    ",
      "scallion",
      "ginger",
      "garlic",
      "oyster sauce",
      "white pepper powder",
      "soy sauce",
    ],
    steps: [
      "Take 5-6 stalks of cilantro, remove the leaves, and keep the stalk. Cut the stalk into strips.",
      "Chop 1 tiny piece of red bell pepper, 1 stalk of scallion, 1 tiny piece of ginger into thin strips. Then chop another 1 stalk of scallion and 1 tiny piece of ginger into mince.",
      "Peel 1 whole garlic, and mince all the garlic cloves. ",
      "Cut 4 chicken leg quarters into medium chunks. ",
      "Add all the scallion, ginger, and garlic mince into a bowl. Then add 3 tablespoons of oyster sauce, 1 tablespoon of white pepper powder, 4 tablespoons of soy sauce. ",
      "Add the cut chicken pieces inside, and mix everything well. Marinate the chicken for 10-15 minutes.",
      "Boil a large pot of water and steam the chicken for 15-20 minutes. Try not to stack the chicken so that it may be cooked unevenly.",
      "After the chicken is cooked, place the chicken and the steam juice on the plate you want to serve. Place the previously chopped cilantro stalk, red bell pepper, ginger, and scallion strips on top of the chicken.",
      "Heat 4-5 tablespoons of vegetable oil in a tiny pan or pot. After the oil starts to smoke, pour the hot oil on the vegetable strips. Now it is ready to serve.",
    ],
    category: Category.CHICKEN,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=rBTu7tyOAhs",
  },
  {
    title: "Northeastern Brine Chicken with chili sauce",
    image: "YanShuiJi",
    difficulity: 2,
    description:
      "This dish originally originated in Nanjing but has been modified in Northeastern cuisine. The tender chicken and perfect level of saltiness will surely whet your appetite.",
    popularity: 3.5,
    ingredients: [
      "chicken leg quarters",
      "scallion",
      "ginger",
      "garlic",
      "cilantro",
      "Sichuan peppercorn",
      "chili powder",
      "soy sauce",
      "Shanxi vinegar",
      "sugar",
      "salt",
      "sesame oil",
    ],
    steps: [
      "Cut 2 stalks of scallions into large chunks. Slice one tiny piece of ginger",
      "Half-fill a large pot or a wok with water. Add 2 chicken leg quarters,  scallion chunks, ginger slices, and 1 tablespoon of Sichuan peppercorn. Bring the water to a boil, and then turn down the heat and let it simmer for 15-20 minutes.",
      "Chop another 2 stalks of scallion into small pieces. Place them in a bowl, and add 1 tablespoon of chili powder. Mix everything well. Then mince 5-6 cloves of garlic.",
      "Heat 5-6 tablespoons of vegetable oil in a pan or a pot. After the oil starts to smoke, pour the oil into the bowl with scallion and cilantro. Then add 2 tablespoons of soy sauce, 2 tablespoons of Shanxi vinegar,  1 teaspoon of sugar, 1 teaspoon of salt, 1 teaspoon of sesame oil, and the garlic mince into the bowl. Mix everything well",
      "After the chicken is cooked, cut the chicken into medium chinks and place them on the serving plate. Chop 5-6 stalks of cilantro into small pieces and sprinkle them on the chicken. Finally, pour the sauce on the chicken, and it's ready to serve.",
    ],
    category: Category.CHICKEN,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=KwSYVpP3t3o",
  },
  {
    title: "Crispy fried pork",
    description:
      "This dish is one of the most famous dishes in Northeastern Chinese cuisine, and it can even be considered one of the most famous dishes in all of Chinese cuisine. If you are not a fan of sweet and sour Chinese dishes, this dish will definitely surprise you and your family.",
    image: "LiuRouDuan",
    difficulity: 5,
    popularity: 5,
    ingredients: [
      "Pork tenderloin (pork chop/pork belly)",
      "Green bell pepper",
      "Red bell pepper",
      "garlic",
      "ginger",
      "scallion",
      "soy sauce",
      "white pepper powder",
      "salt",
      "sugar",
      "Shanxi vinegar",
    ],
    steps: [
      "Cut 0.7 lbs of pork tenderloin into strips. The strips should be 1cm wide and 3cm wide for better results. ",
      "Cut 1 medium piece of green bell pepper and red bell pepper into medium chunks. ",
      "Chop 1 stalk of scallion, 1 tiny piece of ginger into tiny pieces. ",
      "Cut 1 stalk of scallion and 1 tiny piece of ginger into thin strips. Place them in a bowl and add 1/2 teaspoon of salt and 2 tablespoons of water. Rub and squeeze the scallion and ginger strips to squeeze the juice out. Then take out the scallion and ginger and keep the juice.",
      "Place the cut pork in the juice bowl. Then add 2 tablespoons of soy sauce, 1 teaspoon of msg (optional), and 1 teaspoon of white pepper powder. Mix everything well and marinate the meat for 10 minutes.",
      "In another bowl, add 6 teaspoons of water, 1/2 teaspoon of salt, 1 tablespoon of sugar, 3/4 tablespoon of Shanxi vinegar, 2 tablespoons of soy sauce.",
      "In the bowl with marinated meat, add 10 tablespoons of potato starch, 8-9 tablespoons of water, and 3 tablespoons of oil. Mix everything well.",
      "Use a large pot or a wok, and heat a decent amount of oil to 446 F (230 C). Fry half of the marinated pork until they become lightly golden brown. Then reheat the oil and refry the other half of the pork to a light golden brown.",
      "Reheat the oil to 464 F (240 C) and refry all the pork until they become golden brown.",
      "Heat 4-5 tablespoons of oil and cook the chopped scallion and garlic pieces until you smell the fragrance. Then add the pepper chunks and cook for 30 seconds.",
      "Add the fried pork and the mixed sauce inside. Mix everything well and cook for 30 seconds.",
      "Take everything out and start plating.",
    ],
    category: Category.PORK,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=QN0otKfLr0E&t=2s",
    must_know: true,
  },
  {
    title: "Big Plate Chicken",
    image: "DaPanJi",
    description:
      "This dish originally originated from Xinjiang and has been modified in Northeastern Chinese cuisine. It goes exceptionally well with rice and its unique seasoning is sure to make you crave more rice than usual.",
    difficulity: 3,
    popularity: 4.5,
    ingredients: [
      "Chicken leg quarter",
      "Green bell pepper",
      "scallion",
      "garlic",
      "ginger",
      "Sichuan peppercorn",
      "Start anise",
      "Dried chilis",
      "Dried bay leaves",
      "soy sauce",
      "salt",
    ],
    steps: [
      "Cut 2 chicken leg quarters, 2 medium-sized potatoes, and 1 green bell pepper into medium chunks.",
      "Cut 2 stalks of scallion into large chunks and slice 1 tiny piece of ginger. Chop 5-6 cloves of garlic into tiny pieces.",
      "Heat 6-7 tablespoons of oil in a large frying pan or a wok. Add 2-3 dried chilis, 2 star anises, 2 dried bay leaves, and 1 tablespoon of Sichuan peppercorn. Cook them until you smell the fragrance, and then add the chicken pieces and cook for 4-5 minutes.",
      "Add the scallion chunks and ginger slices inside and cook for 1-2 minutes. Then add 4 tablespoons of soy sauce and the chopped potatoes inside and cook for another 3-4 minutes.",
      "Add 1 teaspoon of salt and add water inside until everything is 3/4 immersed under the liquid. Bring everything to a boil, then boil the heat and let it simmer for 20 - 25 minutes.",
      "Pick out all the spices, and then add the chopped bell pepper chunks. Mix everything up and cook for another 2-3 minutes.",
      "Add the chopped garlic and mix everything up nicely. Take everything out and serve. This dish can be served on freshly cooked noodles.",
    ],
    category: Category.CHICKEN,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=Y32-XaP8Z8c",
  },
  {
    title: "Stir-fried Eggs with Scallions",
    description: `
    This dish is made when Chinese people feel lazy to go out shopping for groceries. Despite its simplicity, it is exceptionally delicious.`,
    image: "DaCongChaoJiDan",
    difficulity: 2,
    popularity: 3.5,
    ingredients: [
      "cut scallion, tofu, and cilantro",
      "Sichuan peppercorn",
      "soy sauce",
      "salt",
    ],
    steps: [
      "Cut 3-4 stalks of scallion into medium chunks. ",
      "Crack and whisk 4-5 eggs and whisk the eggs with 1/2 teaspoon of salt.",
      "Heat 3-4 tablespoons of oil in a large frying pan or a wok. When the oil starts to smoke, cook the egg until both sides become lightly golden brown. Use a spatula or a spoon to cut the egg into medium chunks before taking them out.",
      "Reheat 3-4 tablespoons of oil, and add 1 tablespoon of Sichuan peppercorn. Remove the peppercorn when they start to turn dark brown.",
      "Cook the scallion chunks for 1-2 minutes. Then add 2 tablespoons of soy sauce, 1 teaspoon of msg (optional), and 4 tablespoons of water and cook for another 1-2 minutes.",
      "Add the fried egg and keep cooking for 1-2 minutes to let the egg absorb the cooking juice.",
      "Take everything out and serve.",
    ],
    category: Category.VEGETABLE,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=wIMKo0mcnXA&t=440s",
  },
  {
    title: "Tomato and Egg Stir-fry Noodles",
    image: "FanQieJiDanMian",
    description:
      "Tomato and scrambled eggs are one of the most famous dishes in China, and they can pair perfectly with almost any staple food. It is easy to make and also very nutritious. When paired with noodles, it will surely whet your appetite.",
    difficulity: 2,
    popularity: 3,
    ingredients: [
      "cut scallion, tofu, and cilantro",
      "scallion",
      "salt",
      "noodles",
    ],
    steps: [
      "Dice 4-5 medium-sized tomatoes into medium chunks. Chop 1 stalk of scallion into medium chunks. ",
      "Crack and whisk 4-5 eggs with 1/2 teaspoons of salt.",
      "Heat 5-6 tablespoons of oil in a large frying pan or a wok. Fry the egg until both sides become golden brown. Cut the egg into medium chunks using a spatula or a spoon.",
      "Add the chopped scallion inside and cook it for 1 minute. Then add all the chopped tomatoes and 1 1/2 teaspoon of salt and mix everything well. Cook for 1-2 minutes.",
      "Add 4-5 tablespoons of water and bring everything up to boil. Then put on the lid and boil it for 3-4 minutes.",
      "Take off the lid, and add 1 teaspoon of msg (optional). Cook for another 1-2 minutes.",
      "Take everything out and serve with freshly cooked noodles.",
    ],
    category: Category.NOODLE,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=htfPuTHvdN4",
  },
  {
    title: "Braised pork belly",
    image: "HongShaoRou",
    description:
      "This dish is undoubtedly one of the most famous in China. During the poverty-stricken times of several decades ago, this dish brought happiness to many families and became a symbol of joy. Even now, it continues to satisfy the craving for delicious meat and remains a culinary delight in the lives of many people.",
    difficulity: 3,
    popularity: 4,
    ingredients: [
      "Pork belly",
      "scallion",
      "ginger",
      "star anise",
      "Sichuan peppercorn",
      "dried bay leaves",
      "soy sauce",
      "dark soy sauce",
      "salt",
    ],
    steps: [
      "Take 2.2 lbs of pork belly. If there is excess hair on the pork belly skin, use a torch or a razor to remove the hair. Cut the pork belly into 3cm x 3cm squares. ",
      "Chop 2 stalks of scallion and slice 1 tiny piece of ginger.",
      "Heat 5-6 tablespoons of oil in a large frying pan or a wok. Add the pork belly chunks inside and cook until they become golden brown.",
      "Add 3 star anises, 3-4 bay leaves, 1 tablespoon of Sichuan peppercorn, chopped scallion, and ginger slices. Cook everything for 2-3 minutes.",
      "Add 3 tablespoons of soy sauce and 1 tablespoons of dark soy sauce and cook for 1-2 minutes. Then add water until everything is immersed in the liquid.",
      "Bring everything up to boil, and add 1 teaspoon of salt. Turn down the heat and put on the lid to let it simmer for 70-80 minutes.     ",
      "Pick up all the spices and turn up the heat to bring everything to a boil. Keep stirring until the sauce becomes thick and can be coated on the pork belly.",
      "Take everything out and serve.",
    ],
    category: Category.PORK,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=O05EJ0ykVQ8&t=303s",
    must_know: true,
  },
  {
    title: "Braised spare ribs",
    image: "HongShaoPaiGu",
    difficulity: 3,
    popularity: 5,
    description:
      "Chinese people's love for spare ribs began with this dish. With just a few ingredients and simple stir-frying, you can start the slow-cooking process. Time will turn this dish into the star of your dinner.",
    ingredients: [
      "Pork spare ribs",
      "scallion",
      "ginger",
      "star anise",
      "dried bay leaves",
      "soy sauce",
      "dark soy sauce",
      "salt",
    ],
    steps: [
      "Take 2 lbs of spare ribs. Chop the ribs into square chunks.",
      "Chop 2 stalks of scallion and slice 1 tiny piece of ginger.",
      "Half-fill a large pot or a wok with water. Add the chopped ribs inside and bring everything up to boil. Remove the dirty foam while boiling.",
      "Heat 5-6 tablespoons of oil in a large frying pan or a wok. Add the rib chunks inside and cook until they become lightly golden brown.",
      "Add 2 star anises, 3-4 bay leaves, chopped scallion, and ginger slices. Cook everything for 2-3 minutes.",
      "Add 3 tablespoons of soy sauce and 1 tablespoons of dark soy sauce and cook for 1-2 minutes. Then add water until everything is immersed in the liquid.",
      "Bring everything up to boil, and add 1 teaspoon of salt. Turn down the heat and put on the lid to let it simmer for 70-80 minutes.",
      "Pick up all the spices and remove excess fat. Turn up the heat to bring everything to a boil. Keep stirring until the sauce becomes thick and can be coated on the rubs.",
      "Take everything out and serve. ",
    ],
    category: Category.PORK,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=Gb5CAcxcmyw",
    must_know: true,
  },
  {
    title: "Hand-pulled Pork Ribs",
    image: "ShouBaPaiGu",
    description:
      "This dish truly satisfies your craving for meat. Just pick up a spare rib with your hands and take a bite. If you love eating meat, you must give this dish a try.",
    difficulity: 4,
    popularity: 4,
    ingredients: [
      "Pork spare ribs",
      "scallion",
      "ginger",
      "Sichuan peppercorn",
      "star anise",
      "dried bay leaves",
      "Chinese cooking wine",
      "soy sauce",
      "dark soy sauce",
      "salt",
    ],
    steps: [
      "Soak the 3.3 spare ribs in water for 1 hour to remove blood.",
      "Cut 2 stalks of scallion and slice 1 medium piece of ginger.",
      "Heat 7-8 tablespoons of oil in a large wok. Add the scallion chunks, ginger slices, 3 star anises, 5-6 bay leaves, and 1 tablespoon of Sichuan peppercorn. Cook until you smell the fragrance.",
      "Add the spare ribs inside and cook until the ribs become golden brown.",
      "Add 2 tablespoons of Chinese cooking wine, 2 tablespoons of soy sauce, and 1 tablespoon of dark soy sauce. Mix everything well and cook for 2 minutes.",
      "Add water until everything is immersed in the liquid. Bring everything to a boil and add 2 tablespoons of salt.",
      "Put on the lid and turn down the heat. Let it simmer for 70-80 minutes.",
      "Turn off the heat and let the rib rest for 10 minutes.",
      "Take out the rib and start plating.",
    ],
    category: Category.PORK,
    type: Type.MAIN_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=QDljyhAEa00&t=11s",
  },
  {
    title: "scallion mix tofu",
    image: "XiaoCongBanDouFu",
    description:
      "This is a very famous Chinese appetizer. It requires almost no preparation and allows you to enjoy the perfect blend of tofu and green onions. It prepares your palate for the upcoming dishes.",
    difficulity: 1,
    popularity: 4,
    ingredients: ["tofu", "scallion", "cilantro"],
    steps: ["cut scallion, tofu, and cilantro", "boil tofu", "mix together"],
    category: Category.SOY,
    type: Type.APPETIZER,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=QDljyhAEa00&t=11s",
  },

  {
    title: "spicy fried clams",
    image: "LaChaoGuaGa",
    description:
      "This is a very famous appetizer to accompany alcoholic drinks. The freshness of the clams and the spiciness of the seasoning blend together perfectly, making it irresistible.",
    difficulity: 2,
    popularity: 4,
    ingredients: ["clams", "dry chilli", "garlic"],
    steps: ["boil clams", "fried chilli and garlic", "mix together"],
    category: Category.SEAFOOD,
    type: Type.SIDE_DISH,
    recipe_provider_name: "Lao Dong Bei",
    recipe_provider_url: "https://www.youtube.com/@user-ep3ex5xz5r",
    recipe_video_url: "https://www.youtube.com/watch?v=c1SmAXSqkmI",
  },
];
