apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lingta/recipeauth
          env:
            - name: MONGO_URL
              value: "mongodb://auth-mongo-srv:27017/auth?directConnection=true"
            - name: REDIS_URL
              value: "redis://auth-redis-srv:6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: SESSION_SECRET
            - name: SENDGRID_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sendgrid-username
                  key: SENDGRID_USERNAME
            - name: SENDGRID_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snedgrid-password
                  key: SENDGRID_PASSWORD
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: recipe-ne
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
