apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
    spec:
      containers:
        - name: recipe
          image: lingta/recipe
          env:
            - name: MONGO_URL
              value: "mongodb://recipe-mongo-srv:27017/recipe?directConnection=true"
            - name: REDIS_URL
              value: "redis://auth-redis-srv:6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: SESSION_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: recipe-srv
spec:
  selector:
    app: recipe
  ports:
    - name: recipe
      protocol: TCP
      port: 3000
      targetPort: 3000
